# Generated by Django 5.0.6 on 2024-06-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_user',
        ),
    ]
