# Generated by Django 5.0.6 on 2024-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_user',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
