# Generated by Django 5.0.6 on 2024-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_user_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_user',
        ),
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
